### ISSUE TITLE
Cannot Launch mate-bluetooth-properties

### ISSUE THREAD

**Issue by mahiuchun** [mate-desktop-legacy-archive/mate-bluetooth#8] opened 2012-12-05 04:57 UTC
Distribution: Ubuntu 12.10
MATE version: 1.5 installed from "deb http://dev.mate-desktop.org/ubuntu quantal main"

Click "Properties" from mate-blutetooth-applet gives no response.
Try launching "mate-bluetooth-properties" in terminal gives some error message after a while.
http://fpaste.org/6Fc1/

**Comment by stefano-k** [comment] 2012-12-05 14:23
I have it working on debian wheezy. Can you check if the issue is reproducible?

**Comment by mahiuchun** [comment] 2012-12-05 19:13
I've rebooted many times and all the same.

**Comment by stefano-k** [comment] 2012-12-05 19:15
I didnt mean to reboot. You should try on another pc or on a VM

**Comment by mahiuchun** [comment] 2012-12-05 19:33
Another PC is not easy for me. Try a Debian VM is possible.

**Comment by ghost** [comment] 2012-12-05 19:39
When I run it, I do get the window with a message saying I dont have any adapters (which is true); Are you sure that the libunique you have installed has the symbols used during build time?

Make sure you have the package built with libunique and that you have the correct version installed.

**Comment by mahiuchun** [comment] 2012-12-05 20:35
I do have an adapter...

**Comment by stefano-k** [comment] 2012-12-08 17:48
@maxiaojun did you try?

**Comment by mahiuchun** [comment] 2012-12-08 22:53
I tried on an openSUSE 12.1 VM, with the bluetooth device capture into the VM.
The property dialog can pop up correctly.

**Comment by ghost** [comment] 2012-12-08 23:49
@maxiaojun we don't do prisioners in openSUSE :+1:

**Comment by cheater** [comment] 2012-12-15 09:57
Hi, I have found the same to be the case. I'm on Ubuntu 12.04 32-bit. Simply nothing happens when you click on the bluetooth icon and select "Preferences" or "add new device". As a workaround, I can run bluetooth-applet from gnome-bluetooth. It creates another icon (this one looks a bit different actually) and there I can go to preferences and to add a new device.

$ dpkg -S /usr/bin/bluetooth-applet 
gnome-bluetooth: /usr/bin/bluetooth-applet

Running mate-bluetooth-applet from the command line shows this:

$ mate-bluetooth-applet 
*\* Message: adding killswitch idx 4 state KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitch 4 is KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitches state KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitch 4 is KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitches state KILLSWITCH_STATE_UNBLOCKED

There is no output when you select any of the non-working menu items.

**Comment by SnoopDE** [comment] 2013-01-16 13:52
i have the same error on Mint Nadia MATE 32-bit

mate-bluetooth-applet
*\* Message: adding killswitch idx 0 state KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitch 0 is KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitches state KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitch 0 is KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitches state KILLSWITCH_STATE_UNBLOCKED

(mate-bluetooth-properties:3301): Unique-DBus-WARNING **: Error while sending message: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by p4trykx** [comment] 2013-01-26 18:22
I can confirm I have the same problem with Mint 13 Maya 64 bit.  The Mate version is 1.4
The bluetooth icon shows on panel but adding new device does not show anything. I replaced it with gnome-bluetooth package and bluetooth-applet works.

mate-bluetooth-applet
*\* Message: adding killswitch idx 1 state KILLSWITCH_STATE_UNBLOCKED
*\* Message: adding killswitch idx 4 state KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitch 1 is KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitch 4 is KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitches state KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitch 1 is KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitch 4 is KILLSWITCH_STATE_UNBLOCKED
*\* Message: killswitches state KILLSWITCH_STATE_UNBLOCKED

----This is what happens when I i choose "add new device"

(mate-bluetooth-wizard:9608): GLib-GObject-WARNING **: cannot register existing type `BluetoothClient'

(mate-bluetooth-wizard:9608): GLib-CRITICAL **: g_once_init_leave: assertion `result != 0' failed

**Comment by SnoopDE** [comment] 2013-02-01 08:10
fix it by force and hold version v1.2.0-1 from mate-bluetooth + libmatebluetooth

**Comment by sshtmc** [comment] 2013-02-15 11:43
I have the same problem on Ubuntu 12.04 64bit

**Comment by funkypitt** [comment] 2013-03-15 12:15
Same problem here with Mint Maya 32 / Mate 1.4 / mate bluetooth 1.2.1. Any working fix ? How can I apply the suggested fix by SnoopDE? And isn't it time for this to be set on "confirmed"?

**Comment by SnoopDE** [comment] 2013-03-15 21:28
![00001](https://f.cloud.github.com/assets/3285986/265629/3507d86c-8db7-11e2-868b-58020ecea062.png)

**Comment by funkypitt** [comment] 2013-03-15 22:12
Thanks. It works.

**Comment by p4trykx** [comment] 2013-04-06 20:35
I updated to 1.6 and it's still broken. Why does it have an "unconfirmed" label?
Also the workaround while fixing the problem with preferences and adding new device breaks browsing files on the phone. While I can now pair a new phone it's useless because I can't download files from it :/

Failed to mount OBEX volume: Connection refused

**Comment by raveit65** [comment] 2013-04-30 11:02
In fedora 18 mate-bluetooth works for me.
But i used this udev rules from gnome-bluetooth for my rpm.
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/61-mate-bluetooth-rfkill.rules
I install them to /lib/udev/rules.d/61-mate-bluetooth-rfkill.rules .

**Comment by stefano-k** [comment] 2013-04-30 12:08
http://git.mate-desktop.org/debian-packages/plain/mate-bluetooth/debian/61-mate-bluetooth-rfkill.rules

**Comment by stefano-k** [comment] 2013-05-02 14:18
Fixed with latest commits, thanks to m4t

**Closed as completed by stefano-k** 2013-05-02 14:18 UTC
Labels: confirmed bug
